spring:
  application:
    name: feed
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test, keycloak}

  messages:
    basename: i18n/messages

  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: ${keycloak.app.client-id}
          jwk-set-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/certs # JSON Web Key URI to use to verify the JWT token.

  cloud:
    discovery:
      enabled: true
    consul:
      host: ${CONSUL_HOST:http://localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      discovery:
        prefer-ip-address: true

server:
  port: ${SERVER_PORT:8090}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  enable-data-rest: false
  swagger-ui:
    enabled: false

keycloak:
  realm: ${KEYCLOAK_REALM:notice-board}
  auth-url: ${KEYCLOAK_URL:http://localhost:9090}${KEYCLOAK_CONTEXT_PATH:}
  app:
    client-id: ${KEYCLOAK_APP_CLIENT_ID:}
    client-secret: ${KEYCLOAK_APP_CLIENT_SECRET:}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: ${CORS_ALLOWED_METHODS:POST,GET,PUT,OPTIONS,DELETE}
  allowed-credentials: ${CORS_ALLOWED_CREDENTIALS:true}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Access-Control-Allow-Origin,Authorization,Content-Type,Accept-Language}
  max-age: ${CORS_MAX_AGE:200}

rsocket:
  services:
    user-manager: user-manager.UserService
