spring:
  application:
    name: feed
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test, keycloak}

  messages:
    basename: i18n/messages

  cloud:
    consul:
      host: ${CONSUL_HOST:192.168.1.8}
      port: ${CONSUL_PORT:8500}
      enabled: true
    discovery:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: ${keycloak.app.client-id}
          jwk-set-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/certs # JSON Web Key URI to use to verify the JWT token.

keycloak:
  realm: ${KEYCLOAK_REALM:}
  auth-url: ${KEYCLOAK_URL:}${KEYCLOAK_CONTEXT_PATH:}
  app:
    client-id: ${KEYCLOAK_APP_CLIENT_ID:}
    client-secret: ${KEYCLOAK_APP_CLIENT_SECRET:}

server:
  port: ${SERVER_PORT:8090}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  enable-data-rest: false
  swagger-ui:
    enabled: false

rsocket:
  services:
    user-manager: user-manager.UserService

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: ${CORS_ALLOWED_METHODS:}