spring:
  application:
    name: user-manager
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test, keycloak}

  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: ${keycloak.app.client-id}
          jwk-set-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/certs # JSON Web Key URI to use to verify the JWT token.
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${keycloak.rest-admin.client-id}
            client-secret: ${keycloak.rest-admin.client-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/token

  messages:
    basename: i18n/messages

  cloud:
    discovery:
      enabled: true
    consul:
      host: ${CONSUL_HOST:192.168.1.8}
      port: ${CONSUL_PORT:8500}
      enabled: true
      discovery:
        instance-id: ${spring.application.name}-${random.uuid}
        prefer-ip-address: true
        tags: "user-manager.UserService"
        metadata:
          rsocketPort: ${spring.rsocket.server.port}

  rsocket:
    server:
      port: ${RSOCKET_PORT:7070}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  enable-data-rest: false
  swagger-ui:
    enabled: false

keycloak:
  realm: ${KEYCLOAK_REALM:}
  auth-url: ${KEYCLOAK_URL:}${KEYCLOAK_CONTEXT_PATH:}
  app:
    client-id: ${KEYCLOAK_APP_CLIENT_ID:}
    client-secret: ${KEYCLOAK_APP_CLIENT_SECRET:}
  rest-admin:
    client-id: ${KEYCLOAK_CLIENT_ID:}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}

server:
  port: ${SERVER_PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: ${CORS_ALLOWED_METHODS:POST,GET,PUT,OPTIONS,DELETE}
  allowed-credentials: ${CORS_ALLOWED_CREDENTIALS:true}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Access-Control-Allow-Origin,Authorization,Content-Type,Accept-Language}
  max-age: ${CORS_MAX_AGE:200}
